name: Publicar imagem do Docker

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Enviar imagem do Docker para o Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checar o Repositório
        uses: actions/checkout@v3
      
      - name: Logar no Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extrai metadados (tags, rótulos) para o Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ronnyjss/php-laravel
      
      - name: Cria e envie a imagem do Docker
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
